spring:
  profiles:
    active:
      - dev
---
server:
  port: 9201
spring:
  profiles: dev
  application:
    name: mic-test-dev
---
server:
  port: 9202
spring:
  profiles: default
  application:
    name: mic-test-default